version: '3.9'
services:
  my-sql:
    image: mysql
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABSE: blog_nestjs_nextjs
      MYSQL_USER: thang
      MYSQL_PASSWORD: vothang104
    volumes:
      - /home/thang/mysql/blog:/var/lib/mysql
# login to mysql terminal: docker exec -it ID_CONTAINER mysql -uroot -p
  redis:  
    image: redis
    volumes:
      - /home/thang/redis:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379/tcp"